name: Docker Build and Publish Web

on:
  push:
    tags:
      - 'v*'
    paths:
      - 'web/**'
      - 'cmd/**'
      - 'internal/**'
      - 'pkg/**'
      - 'deploy/docker/**'
      - 'go.mod'
      - 'go.sum'
  workflow_dispatch:

env:
  DOCKER_HUB_USERNAME: ifuryst
  ALIYUN_REGISTRY: registry.ap-southeast-1.aliyuncs.com/amoylab
  BUILDX_NO_DEFAULT_ATTESTATIONS: 1
  PUSH_LATEST: ${{ github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v') }}
  SHOULD_LOGIN: ${{ github.event_name == 'push' || github.event_name == 'workflow_dispatch' }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          platforms: linux/amd64,linux/arm64

      - name: Set lowercase repository
        run: echo "LOWERCASE_REPO=$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

      - name: Login to GitHub Container Registry
        if: env.SHOULD_LOGIN == 'true'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push web image (with apiserver)
        uses: docker/build-push-action@v5
        with:
          context: .
          file: deploy/docker/multi/web/Dockerfile
          push: true
          platforms: linux/amd64,linux/arm64
          cache-from: type=gha
          cache-to: type=gha,mode=max
          tags: |
            ${{ env.PUSH_LATEST == 'true' && format('ghcr.io/{0}/web:latest', env.LOWERCASE_REPO) || '' }}
            ${{ format('ghcr.io/{0}/web:{1}', env.LOWERCASE_REPO, github.ref_name) }}
